server:
  port: 8000
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源 ， serverTimeZone中的2B是字符集编码格式，转换后是“+”，新版本的驱动必须要加时区
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
  application:   #定义服务名称, 必须定义
    name: provider-user

mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo #别名包， 因为导入了springcloud-1-api依赖，所以可以直接写路径
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka    #/eureka为内部通信的地址，在浏览器中访问时，不需要加此地址
  instance:
    instance-id: provider-user-8000                #定义微服务的名称，多个服务id必须不同
    prefer-ip-address: true                        #是否显示IP和端口


#test rebase again work
#A
#B
#C
#D
#E
#F
#G
#H
#I
#J
#K
#L
#M

